### ISSUE TITLE
Upgrade android billingclient library

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/lib-aeapps#29]
Looks like a never version of the `com.android.billingclient:billing` is available now.

https://developer.android.com/google/play/billing/billing_library_overview

**Comment by misilehner** [comment]
http://midhunhk.github.io/lib-aeapps/

**Comment by midhunhk** [comment]
_Reminder: Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer._

Aw! They have come out with PBL 3.0, when we haven't even upgraded from 1.0 to 2.0

https://developer.android.com/google/play/billing/integrate

**Comment by midhunhk** [comment]
https://github.com/android/play-billing-samples  
https://developer.android.com/google/play/billing/integrate
